"""add unique constraint uq_stops_route_sequence (route_id, sequence)"""

from alembic import op

# -----------------------------------------------------------------------------
# IMPORTANT:
# - revision must be a unique string (normally generated by Alembic)
# - down_revision should be the previous revision id
#   If this is your FIRST migration, set down_revision = None
# -----------------------------------------------------------------------------
revision = "20260228_uniq_stop_route_seq"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # SQLite needs batch_alter_table for ALTER operations safely
    with op.batch_alter_table("stops") as batch_op:
        batch_op.create_unique_constraint(
            "uq_stops_route_sequence",
            ["route_id", "sequence"],
        )


def downgrade() -> None:
    with op.batch_alter_table("stops") as batch_op:
        batch_op.drop_constraint("uq_stops_route_sequence", type_="unique")